name: "build-docker-image"
description: "Builds a docker image"
inputs:
  name:
    description: "Name of the image"
    required: false
    default: "${{ env.GITHUB_REPOSITORY }}"
  context:
    description: "The folder to use as context"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Set up Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.actor }}/${{ inputs.name }}
        tags: |
          type=sha
          type=raw,value=latest
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
